const people = [
  {
    "name": "Jesus Christ",
    "birth_range": [-4, 0],
    "death_range": [29, 33],
    "category": ["son_of_god"],
    "biography": "Our Lord Jesus Christ, the eternal Son and Word of God, our Lord and God and Savior, who for us men and for our salvation became truly man, was crucified, died, and rose again.",
    "image": "jesus_christ.jpg",
    "date_basis": "traditional",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "",
    "p": 0,
  },
  {
    "name": "Mary the Theotokos",
    "birth_range": [-25, -15],
    "death_range": [40, 60],
    "category": ["mother_of_god"],
    "biography": "The Most Holy Virgin Mary, Theotokos and Ever-Virgin, who gave birth in the flesh to our Lord Jesus Christ and remained with the apostles and the Church after His Resurrection and Ascension.",
    "image": "theotokos.jpg",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "The New Testament does not give a date of death; later traditions differ.",
    "p": 1
  },
  {
    "name": "John the Baptist",
    "birth_range": [-4, 0],
    "death_range": [26, 30],
    "category": ["prophet", "martyr", "missionary"],
    "biography": "The forerunner and baptist of the Lord.",
    "date_basis": "traditional",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "",
    "p": 1,
  },
  {
    "name": "Peter",
    "birth_range": [1, 10],
    "death_range": [64, 67],
    "category": ["apostle", "bishop", "martyr"],
    "biography": "The foremost among the Apostles and a chief witness of the Resurrection, who preached the Gospel, helped establish the Church in Antioch, and later ministered in Rome, where he was martyred for Christ.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The traditional date of martyrdom under Nero is approximately 64–67.",
    "p": 1
  },
  {
    "name": "John",
    "birth_range": [5, 15],
    "death_range": [95, 100],
    "category": ["apostle", "evangelist", "writer"],
    "biography": "One of the Twelve Apostles, the beloved disciple, Evangelist, and the author of the Gospel according to John, the three Catholic Epistles, and the Apocalypse; he ministered especially among the churches of Asia Minor.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Tradition places his death during the reign of Trajan, commonly around 98–100.",
    "p": 1
  },
  {
    "name": "James the brother of the Lord",
    "birth_range": [-10, 10],
    "death_range": [62, 62],
    "category": ["bishop", "martyr", "writer"],
    "biography": "The righteous James, the brother of the Lord—not His biological brother, but a kinsman, and the first bishop of Jerusalem. He presided among the Christians of Jerusalem and was martyred for Christ.  (Orthodox tradition commonly understands him as a son of Joseph by a previous marriage, while St. Jerome proposed a cousin relationship.)",
    "date_basis": "early_historical_tradition",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "His death in Jerusalem is reported by Josephus and other early sources.",
    "p": 1
  },
  {
    "name": "Paul",
    "birth_range": [5, 10],
    "death_range": [64, 67],
    "category": ["apostle", "missionary", "writer", "martyr"],
    "biography": "The holy Apostle Paul, called by Christ to be the Apostle to the Gentiles, a tireless preacher of the Gospel and author of many New Testament Epistles. He was martyred in Rome under Nero.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally martyred in Rome under Nero.",
    "p": 1
  },
  {
    "name": "Matthew",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "evangelist", "writer", "missionary", "martyr"],
    "biography": "One of the Twelve Apostles and Evangelists, the author of the Gospel according to Matthew. He preached Christ beyond Palestine and is traditionally remembered as a martyr.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The location and date of his death are uncertain.",
    "p": 1
  },
  {
    "name": "Luke",
    "birth_range": [5, 15],
    "death_range": [80, 90],
    "category": ["evangelist", "writer", "missionary", "martyr"],
    "biography": "A physician and companion of the holy Apostle Paul, and the Evangelist and author of the Gospel according to Luke and the Acts of the Apostles.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The traditional date of death is often placed around 84.",
    "p": 1
  },
  {
    "name": "Mark",
    "birth_range": [5, 15],
    "death_range": [65, 80],
    "category": ["evangelist", "writer", "missionary", "bishop", "martyr"],
    "biography": "The holy Evangelist Mark, a companion of the Apostles Peter and Paul and traditionally the author of the Gospel according to Mark. He preached Christ in Egypt and is traditionally regarded as the founder and first bishop of the Church of Alexandria.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The identification of Mark with John Mark is traditional and widely accepted.",
    "p": 1
  },
  {
    "name": "Andrew",
    "birth_range": [-5, 5],
    "death_range": [60, 70],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "The First-Called among the Apostles, brother of the Apostle Peter, who preached the Gospel in many lands. Ancient Church tradition especially associates his apostolic labors with the regions around the Black Sea and with Greece, where he was martyred.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Traditional accounts of his later missionary activity and martyrdom vary.",
    "p": 2
  },
  {
    "name": "Thomas",
    "birth_range": [1, 10],
    "death_range": [65, 75],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve Apostles, who confessed the risen Christ with the words, 'My Lord and my God!' Ancient Church tradition strongly associates his apostolic preaching with Mesopotamia and India, where he was martyred.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The tradition of his Indian mission is ancient, though details are difficult to verify.",
    "p": 2
  },
  {
    "name": "Philip",
    "birth_range": [1, 15],
    "death_range": [70, 90],
    "category": ["apostle", "missionary"],
    "biography": "One of the Twelve Apostles, who preached the Gospel in the lands assigned to him by the apostolic mission. Ancient tradition associates his ministry and martyrdom especially with Asia Minor.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Some traditions may conflate him with Philip the evangelist.",
    "p": 2
  },
  {
    "name": "Bartholomew",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve Apostles, who preached the Gospel in the East. Ancient Church tradition associates his apostolic labors with Armenia, India, and other eastern lands, where he suffered martyrdom.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "The details of his later life and death are highly uncertain.",
    "p": 2
  },
  {
    "name": "James son of Alphaeus",
    "birth_range": [1, 15],
    "death_range": [50, 100],
    "category": ["apostle", "missionary"],
    "biography": "One of the Twelve Apostles. The New Testament records little of his later life, but the Church has preserved traditions concerning his apostolic preaching and martyrdom.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "Later traditions about his ministry and death vary considerably.",
    "p": 2
  },
  {
    "name": "James son of Zebedee",
    "birth_range": [-5, 5],
    "death_range": [42, 44],
    "category": ["apostle", "martyr"],
    "biography": "One of the Twelve Apostles and brother of the Apostle John, the first of the Twelve to suffer martyrdom, being put to death by Herod Agrippa I.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Acts 12 records his execution by Herod Agrippa I.",
    "p": 2
  },
  {
    "name": "Jude / Thaddeus",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve Apostles, traditionally identified with the Apostle Jude, brother of James. He preached the Gospel in the East and is traditionally remembered as a martyr.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The identification of various New Testament figures named Jude or Judas is complex.",
    "p": 2
  },
  {
    "name": "Simon the Zealot",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve Apostles, who preached the Gospel after Pentecost and is traditionally remembered as a martyr for Christ.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "His later life is poorly documented.",
    "p": 2
  },
  {
    "name": "Ignatius of Antioch",
    "birth_range": [35, 50],
    "death_range": [107, 117],
    "category": ["bishop", "martyr", "writer"],
    "biography": "Bishop of Antioch who wrote seven major letters while being taken to Rome for martyrdom.  Traditionally the disciple of the apostle John.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "p": 2
  },
  {
    "name": "Matthias",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "martyr"],
    "biography": "Chosen by the Apostles, by prayer and the casting of lots, to take the place among the Twelve left vacant by Judas Iscariot. He preached the Gospel and is traditionally remembered as a martyr.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "p": 3
  },
  {
    "name": "Barnabas",
    "birth_range": [5, 10],
    "death_range": [60, 70],
    "category": ["missionary", "martyr"],
    "biography": "A Levite from Cyprus, surnamed Barnabas by the Apostles, a companion and fellow laborer of the Apostle Paul, and a major preacher of the Gospel in the first Christian generation. Ancient tradition especially associates his later ministry with Cyprus.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "p": 4
  },
  {
    "name": "Linus",
    "birth_range": [10, 20],
    "death_range": [76, 80],
    "category": ["bishop", "martyr"],
    "biography": "Traditionally regarded as the first bishop of Rome after the Apostle Peter and one of the earliest leaders of the Roman Church.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "Mentioned by Paul in 2 Timothy 4:21.",
    "p": 3
  },
  {
    "name": "Anacletus / Cletus",
    "birth_range": [20, 30],
    "death_range": [88, 92],
    "category": ["bishop"],
    "biography": "Traditionally the second bishop of Rome after Linus.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "Ancient sources differ over whether Anacletus and Cletus were the same person.",
    "p": 4
  },
  {
    "name": "Clement of Rome",
    "birth_range": [35, 45],
    "death_range": [100, 102],
    "category": ["bishop", "writer", "martyr"],
    "biography": "The holy Clement, Bishop of Rome and a disciple of the Apostles, traditionally associated with the apostolic succession after Peter. His First Epistle to the Corinthians is one of the earliest surviving witnesses of the post-apostolic Church.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally associated with the third position in the Roman succession after Peter.",
    "p": 3
  },
  {
    "name": "Evodius of Antioch",
    "birth_range": [20, 30],
    "death_range": [66, 69],
    "category": ["bishop", "martyr"],
    "biography": "Traditionally regarded as the first bishop of Antioch after the Apostle Peter and an early shepherd of the Church in Syria.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "p": 4
  },
  {
    "name": "Hero of Antioch",
    "birth_range": [60, 70],
    "death_range": [120, 140],
    "category": ["bishop"],
    "biography": "Traditionally the successor of Ignatius as bishop of Antioch.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "Little securely known.",
    "p": 4
  },
  {
    "name": "Simeon of Jerusalem",
    "birth_range": [1, 10],
    "death_range": [107, 117],
    "category": ["bishop", "martyr"],
    "biography": "A kinsman of the Lord and successor to the Apostle James as bishop of Jerusalem. He is traditionally remembered as a martyr who suffered under the Emperor Trajan.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "Eusebius preserves traditions concerning his succession and martyrdom.",
    "p": 4
  },
  {
    "name": "Polycarp of Smyrna",
    "birth_range": [65, 75],
    "death_range": [155, 160],
    "category": ["bishop", "martyr", "writer"],
    "biography": "The holy Bishop and martyr Polycarp of Smyrna, a disciple of the Apostle and Evangelist John and a teacher of the apostolic faith. He suffered martyrdom at an advanced age, refusing to deny Christ.  'The Martyrdom of Polycarp' is one of the earliest surviving Christian martyrdom accounts.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "p": 2
  },
  {
    "name": "Papias of Hierapolis",
    "birth_range": [60, 70],
    "death_range": [130, 140],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Hierapolis who diligently received and preserved traditions concerning the Apostles and the apostolic generation, and wrote an early exposition of the sayings of the Lord.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His major work survives only in fragments quoted by later authors.",
    "p": 4
  },
  {
    "name": "Quadratus of Athens",
    "birth_range": [70, 80],
    "death_range": [125, 140],
    "category": ["writer", "bishop"],
    "biography": "Early Christian apologist who presented a defense of Christianity to Emperor Hadrian.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Often regarded as one of the earliest named Christian apologists.",
    "p": 4
  },
  {
    "name": "Aristides of Athens",
    "birth_range": [75, 85],
    "death_range": [125, 150],
    "category": ["writer", "philosopher"],
    "biography": "Christian philosopher and apologist who defended Christianity before the emperor.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The details of his life are sparse.",
    "p": 4
  },
  {
    "name": "Hermas",
    "birth_range": [70, 80],
    "death_range": [140, 150],
    "category": ["writer", "prophet"],
    "biography": "Roman Christian associated with the Shepherd of Hermas, an influential early Christian prophetic work.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The work itself is better attested than the author's biography.",
    "p": 2
  },
  {
    "name": "Justin Martyr",
    "birth_range": [95, 105],
    "death_range": [165, 167],
    "category": ["writer", "philosopher", "martyr"],
    "biography": "The holy Martyr Justin, a Christian philosopher and apologist who confessed Christ before the pagan world and bore witness to the worship and faith of the Church. He was martyred in Rome under Marcus Aurelius.",
    "date_basis": "historical",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His martyrdom under Marcus Aurelius is well established.",
    "p": 2
  },
  {
    "name": "Irenaeus of Lyons",
    "birth_range": [130, 140],
    "death_range": [195, 205],
    "category": ["bishop", "writer", "martyr"],
    "biography": "The holy Irenaeus, Bishop of Lyons, disciple of the disciples of the Apostles and a great defender of the apostolic faith. He defended the rule of faith, apostolic succession, and the unity of the Church against the Gnostic heresies.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "p": 2
  },
  {
    "name": "Hegesippus",
    "birth_range": [110, 120],
    "death_range": [175, 185],
    "category": ["writer"],
    "biography": "Early Christian historian who traveled among churches and collected traditions concerning the apostolic age.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings survive only in fragments.",
    "p": 3
  },
  {
    "name": "Aquila",
    "birth_range": [10, 20],
    "death_range": [60, 80],
    "category": ["missionary"],
    "biography": "A Jewish Christian and fellow laborer of the Apostle Paul, who, together with his wife Priscilla, served the Church as a missionary and apostolic worker.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "Mentioned several times in the Pauline letters and Acts.",
    "p": 4
  },
  {
    "name": "Priscilla",
    "birth_range": [10, 20],
    "death_range": [60, 80],
    "category": ["missionary", "apostolic_worker"],
    "biography": "A faithful Christian woman and fellow laborer of the Apostle Paul who, together with her husband Aquila, served the Church as a missionary and teacher in the apostolic communities.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "p": 4
  },
  {
    "name": "Silas / Silvanus",
    "birth_range": [10, 20],
    "death_range": [60, 75],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Missionary companion of Paul and important early Christian messenger.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The identification of Silas with Silvanus is traditional and widely accepted.",
    "p": 4
  },
  {
    "name": "Titus",
    "birth_range": [10, 20],
    "death_range": [90, 100],
    "category": ["bishop", "missionary"],
    "biography": "A trusted disciple and fellow laborer of the Apostle Paul, a true son in the faith, whom Paul entrusted with the pastoral care of the Church in Crete. He is traditionally regarded as its first bishop.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His later episcopal role is primarily preserved in tradition.",
    "p": 4
  },
  {
    "name": "Timothy",
    "birth_range": [20, 30],
    "death_range": [90, 100],
    "category": ["bishop", "missionary", "martyr"],
    "biography": "A beloved disciple and close fellow laborer of the Apostle Paul, whom Paul ordained and entrusted with the pastoral care of the Church in Ephesus. He is traditionally regarded as its first bishop.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The New Testament gives substantial information about his relationship with Paul.",
    "p": 4
  },
  {
    "name": "Tychicus",
    "birth_range": [20, 30],
    "death_range": [70, 90],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Pauline co-worker and messenger associated with several apostolic letters.",
    "date_basis": "historical_tradition",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "His later life is unknown.",
    "p": 5
  },
  {
    "name": "Onesimus",
    "birth_range": [30, 40],
    "death_range": [90, 110],
    "category": ["bishop", "martyr"],
    "biography": "Traditionally identified with the Onesimus mentioned by the Apostle Paul in his Epistle to Philemon and later remembered in the Church as a bishop and faithful servant of Christ.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The identification of the Onesimus of Philemon with the later bishop is traditional but not certain.",
    "p": 4
  },
  {
    "name": "Dionysius the Areopagite",
    "birth_range": [10, 20],
    "death_range": [80, 100],
    "category": ["bishop", "missionary", "martyr"],
    "biography": "A member of the Athenian Areopagus who believed in Christ through the preaching of the Apostle Paul. Ancient Church tradition remembers him as a missionary and bishop in Athens.",
    "date_basis": "mixed_historical_tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The later biography is difficult to distinguish from subsequent legendary development.",
    "p": 4
  },
  {
    "name": "Pantaenus",
    "birth_range": [100, 110],
    "death_range": [190, 210],
    "category": ["missionary", "writer"],
    "biography": "Leading figure in the Alexandrian catechetical tradition and missionary to the East.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Associated with the early development of Christian intellectual life in Alexandria.",
    "p": 4
  },
  {
    "name": "Theophilus of Antioch",
    "birth_range": [115, 125],
    "death_range": [180, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop and early Christian apologist who wrote for a pagan intellectual audience.",
    "date_basis": "historical",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Active in the later second century.",
    "p": 4
  },

  {
    "name": "Athenagoras of Athens",
    "birth_range": [125, 135],
    "death_range": [185, 195],
    "category": ["philosopher", "writer"],
    "biography": "Christian philosopher and apologist who wrote a sophisticated defense of Christianity for the pagan intellectual world.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Author of the Plea for the Christians and a work on the resurrection of the dead; his dates are approximate.",
    "p": 4
  },
  {
    "name": "Tatian the Syrian",
    "birth_range": [110, 120],
    "death_range": [170, 180],
    "category": ["apologist", "writer"],
    "biography": "A Syrian Christian intellectual and disciple of the holy Martyr Justin, author of the Diatessaron, an early harmony of the four Gospels. Later in life he fell into Encratite error, and his later deviation should not obscure the importance of his earlier service to the Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Later associated with Encratite tendencies, but his earlier work represents an important stage in the development of Christian literary culture.",
    "p": 4
  },
  {
    "name": "Melito of Sardis",
    "birth_range": [95, 105],
    "death_range": [180, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Sardis and influential Christian writer whose surviving Paschal homily is one of the earliest substantial examples of Christian theological preaching.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "An important witness to second-century theology, especially concerning Christ and Pascha.",
    "p": 3
  },
  {
    "name": "Dionysius of Corinth",
    "birth_range": [100, 110],
    "death_range": [170, 180],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Corinth whose letters to churches across the Christian world demonstrate communication and mutual awareness among distant Christian communities.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings survive only in fragments, but Eusebius regarded him as an important second-century church leader.",
    "p": 4
  },
  {
    "name": "Apollinaris of Hierapolis",
    "birth_range": [120, 130],
    "death_range": [175, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop and Christian apologist who wrote against paganism and defended the Christian faith during the reign of Marcus Aurelius.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings are largely lost but he was regarded as a significant early Christian author.",
    "p": 5
  },
  {
    "name": "Polycrates of Ephesus",
    "birth_range": [125, 135],
    "death_range": [195, 205],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Ephesus who defended the Asian Christian tradition concerning the date of Pascha in correspondence with Rome.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Represents the continuing strength of the Johannine churches in Asia Minor.",
    "p": 5
  },
  {
    "name": "Clement of Alexandria",
    "birth_range": [145, 155],
    "death_range": [215, 220],
    "category": ["writer"],
    "biography": "Major Christian teacher in Alexandria who sought to show how the truths of the Christian faith could engage and transform the best of Greek philosophy and classical learning.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Slightly later than the core apostolic and immediate post-apostolic period, but an important bridge into the mature intellectual tradition of the early Church.",
    "p": 3
  },
  {
    "name": "Abercius of Hierapolis",
    "birth_range": [90, 105],
    "death_range": [170, 200],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Hierapolis associated with an early Christian funerary inscription describing the Christian world as a connected community united by faith and Eucharistic fellowship.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The Abercius inscription is an important early witness to Christian self-understanding and pilgrimage.",
    "p": 5
  },
  {
    "name": "Marcion of Sinope",
    "birth_range": [80, 90],
    "death_range": [150, 160],
    "category": ["teacher", "writer", "heretic"],
    "biography": "A second-century teacher who fell into grave heresy by rejecting the God of the Old Testament as the Father of Jesus Christ and mutilating the apostolic faith and Scriptures to fit his teaching. His movement caused serious harm to the Church and was decisively rejected by the catholic Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Not part of the catholic succession, but historically important for understanding the development of the New Testament canon and orthodox responses to competing interpretations of Christianity.",
    "p": 4
  },
  {
    "name": "Valentinus",
    "birth_range": [95, 105],
    "death_range": [160, 170],
    "category": ["writer", "heretic"],
    "biography": "A prominent second-century teacher who departed from the apostolic faith and became the leading figure associated with the Valentinian Gnostic heresy, whose elaborate speculations about God, creation, and salvation were opposed by the Fathers of the Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Useful for understanding the theological environment against which Irenaeus and other orthodox writers argued.",
    "p": 3
  },
  {
    "name": "Basilides",
    "birth_range": [100, 115],
    "death_range": [140, 160],
    "category": ["teacher", "writer", "heretic"],
    "biography": "An Alexandrian teacher who propagated a Gnostic system contrary to the apostolic faith. His teachings were among the many distortions of Christianity against which the Church defended the truth of the Gospel.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His inclusion is useful for showing the diversity of competing Christian interpretations in the second century.",
    "p": 4
  },
  {
    "name": "Ptolemy the Valentinian",
    "birth_range": [100, 120],
    "death_range": [160, 180],
    "category": ["teacher", "writer", "heretic"],
    "biography": "A prominent teacher of the Valentinian Gnostic heresy whose writings expressed teachings contrary to the apostolic faith concerning God, creation, revelation, and salvation.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "His exact biography is uncertain, but he is an important representative of the Valentinian movement.",
    "p": 5
  },
  {
    "name": "Soter of Rome",
    "birth_range": [100, 110],
    "death_range": [174, 182],
    "category": ["bishop"],
    "biography": "Bishop of Rome in the later second century, remembered for his concern for other churches and his correspondence with the church of Corinth.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "A useful figure for illustrating the growing interconnection of major Christian churches.",
    "p": 5
  },
  {
    "name": "Eleutherus of Rome",
    "birth_range": [110, 120],
    "death_range": [189, 189],
    "category": ["bishop"],
    "biography": "Bishop of Rome during the late second century and a contemporary of Irenaeus.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His episcopate falls near the period when catholic Christian structures and identity were becoming increasingly explicit.",
    "p": 5
  },

  // EMPERORS
  {
    "name": "Augustus",
    "birth_range": [-63, -63],
    "death_range": [14, 14],
    "category": ["emperor"],
    "p": 4,
    "biography": "The first Roman emperor, ruling from 27 BC to AD 14. He established the imperial system under which Christ was born and presided over the period of relative stability known as the Pax Romana."
  },
  {
    "name": "Tiberius",
    "birth_range": [-42, -42],
    "death_range": [37, 37],
    "category": ["emperor"],
    "p": 3,
    "biography": "Roman emperor from AD 14 to 37. He ruled during the public ministry, Crucifixion, Resurrection, and Ascension of Jesus Christ."
  },
  {
    "name": "Claudius",
    "birth_range": [-10, -10],
    "death_range": [54, 54],
    "category": ["emperor"],
    "p": 4,
    "biography": "Roman emperor from AD 41 to 54. His reign saw the early expansion of the Christian mission and the growth of the Church in Rome, while the expulsion of Jews from Rome created an important setting for the early Christian community there."
  },
  {
    "name": "Nero",
    "birth_range": [37, 37],
    "death_range": [68, 68],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 54 to 68. Following the great fire of Rome in AD 64, he authorized a major persecution of Christians in Rome, traditionally associated with the martyrdoms of the apostles Peter and Paul."
  },
  {
    "name": "Vespasian",
    "birth_range": [9, 9],
    "death_range": [79, 79],
    "category": ["emperor"],
    "p": 4,
    "biography": "Roman emperor from AD 69 to 79 and founder of the Flavian dynasty. He commanded the Roman campaign against the Jewish revolt before becoming emperor, leading to the destruction of Jerusalem and the Temple in AD 70."
  },
  {
    "name": "Titus (emperor)",
    "birth_range": [39, 39],
    "death_range": [81, 81],
    "category": ["emperor"],
    "p": 3,
    "biography": "Roman emperor from AD 79 to 81. As commander under his father Vespasian, he led the Roman conquest of Jerusalem and the destruction of the Temple in AD 70."
  },
  {
    "name": "Domitian",
    "birth_range": [51, 51],
    "death_range": [96, 96],
    "category": ["emperor", "persecutor"],
    "p": 4,
    "biography": "Roman emperor from AD 81 to 96. His reign is associated with imperial pressure against some Christians and with the broader development of the imperial cult, although the extent of any systematic persecution of Christians remains debated."
  },
  {
    "name": "Trajan",
    "birth_range": [53, 53],
    "death_range": [117, 117],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 98 to 117. His correspondence with Pliny the Younger established an important early imperial policy toward Christians: they were not to be actively sought out, but those formally accused and refusing to renounce Christianity could be punished."
  },
  {
    "name": "Hadrian",
    "birth_range": [76, 76],
    "death_range": [138, 138],
    "category": ["emperor"],
    "p": 3,
    "biography": "Roman emperor from AD 117 to 138. His reign included the Bar Kokhba Revolt and the transformation of Jerusalem into the Roman colony of Aelia Capitolina; his policy toward Christians was generally more tolerant than periods of active persecution."
  },
  {
    "name": "Antoninus Pius",
    "birth_range": [86, 86],
    "death_range": [161, 161],
    "category": ["emperor"],
    "p": 5,
    "biography": "Roman emperor from AD 138 to 161. His reign was generally peaceful and does not appear to have been marked by a systematic empire-wide persecution of Christians; Christian apologists such as Justin Martyr addressed the imperial administration during this period."
  },
  {
    "name": "Marcus Aurelius",
    "birth_range": [121, 121],
    "death_range": [180, 180],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 161 to 180. Although there was no continuous empire-wide persecution throughout his reign, several significant local persecutions occurred, including the martyrdom of Justin Martyr and the major persecution at Lyons and Vienne in AD 177."
  },
  {
    "name": "Commodus",
    "birth_range": [161, 161],
    "death_range": [192, 192],
    "category": ["emperor"],
    "p": 4,
    "biography": "Roman emperor from AD 180 to 192. His reign was generally more favorable to Christians than that of his father Marcus Aurelius, and members of the imperial household are associated with Christianity in early sources."
  },
  {
    "name": "Septimius Severus",
    "birth_range": [145, 145],
    "death_range": [211, 211],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 193 to 211 and founder of the Severan dynasty. His reign saw significant persecution of Christians, particularly around AD 202–203, including the martyrdoms of Perpetua and Felicity."
  },
  {
    "name": "Alexander Severus",
    "birth_range": [208, 208],
    "death_range": [235, 235],
    "category": ["emperor"],
    "p": 4,
    "biography": "Roman emperor from AD 222 to 235. His reign was relatively favorable toward Christianity, and Christian tradition remembers the period as one of religious tolerance, although the details of his personal religious views are difficult to establish."
  },
  {
    "name": "Decius",
    "birth_range": [201, 201],
    "death_range": [251, 251],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 249 to 251. He initiated the first empire-wide persecution requiring citizens to perform public sacrifice, producing the major Christian crisis of the lapsi and the martyrdom of numerous Christians."
  },
  {
    "name": "Valerian",
    "birth_range": [200, 200],
    "death_range": [260, 260],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 253 to 260. He initiated a major persecution of Christians beginning in AD 257, targeting clergy and later requiring sacrifices, and the persecution produced the martyrdom of figures including Cyprian of Carthage."
  },
  {
    "name": "Gallienus",
    "birth_range": [218, 218],
    "death_range": [268, 268],
    "category": ["emperor"],
    "p": 3,
    "biography": "Roman emperor from AD 253 to 268, initially ruling with his father Valerian. Around AD 260 he ended the Valerian persecution and granted Christians a prolonged period of legal toleration, marking a major turning point in the Church's relationship with the Roman state."
  },
  {
    "name": "Diocletian",
    "birth_range": [244, 244],
    "death_range": [311, 311],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 284 to 305 and architect of the Tetrarchy. In AD 303 he initiated the Great Persecution, the most extensive and systematic imperial attempt to suppress Christianity."
  },
  {
    "name": "Galerius",
    "birth_range": [260, 260],
    "death_range": [311, 311],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Caesar from AD 293 and Augustus from AD 305 to 311. He was one of the principal architects and enforcers of the Great Persecution, but shortly before his death he issued the Edict of Serdica in AD 311, ending the persecution and granting Christians toleration."
  },
  {
    "name": "Licinius",
    "birth_range": [265, 265],
    "death_range": [325, 325],
    "category": ["emperor", "persecutor"],
    "p": 3,
    "biography": "Roman emperor from AD 308 to 324 and colleague of Constantine in the settlement associated with the Edict of Milan in AD 313. He initially permitted Christian freedom but later came into conflict with Constantine and imposed renewed restrictions on Christians in his territories before his defeat."
  },
  {
    "name": "Constantine the Great",
    "birth_range": [272, 274],
    "death_range": [337, 337],
    "category": ["emperor", "political_ruler"],
    "biography": "Roman emperor who ended the great persecutions, legalized Christianity, and convened the Council of Nicaea.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "A decisive political figure in the transition from the persecuted Church to the publicly established Christian Church.",
    "p": 2
  },
//  {
//    "name": "Constantius II",
//    "birth_range": [317, 317],
//    "death_range": [361, 361],
//    "category": ["emperor", "political_ruler"],
//    "biography": "Roman emperor whose reign was dominated by conflict between Nicene and various non-Nicene Christian factions.",
//    "date_basis": "historical",
//    "date_confidence": "high",
//    "identity_confidence": "high",
//    "notes": "Not a Church figure, but highly relevant to the political history of the Nicene controversy.",
//    "p": 5
//  },

  {
    "name": "Tertullian",
    "birth_range": [155, 165],
    "death_range": [220, 225],
    "category": ["writer"],
    "biography": "A prolific North African Christian writer whose theological vocabulary profoundly influenced Latin Christianity. In later life he departed from the catholic Church and embraced Montanist rigorism; his considerable earlier contributions must therefore be distinguished from his later ecclesiastical and theological deviation.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His later association with Montanism complicated his standing in the Church.",
    "p": 3
  },
  {
    "name": "Hippolytus of Rome",
    "birth_range": [165, 175],
    "death_range": [235, 235],
    "category": ["bishop", "writer", "martyr"],
    "biography": "A major Roman theologian and writer who became involved in a serious schism in opposition to the Roman episcopate. He was eventually reconciled to the Church and is traditionally remembered as a martyr.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "medium",
    "notes": "His precise ecclesiastical status and the details of his reconciliation remain debated.",
    "p": 3
  },
  {
    "name": "Origen of Alexandria",
    "birth_range": [184, 186],
    "death_range": [253, 254],
    "category": ["teacher", "writer"],
    "biography": "A highly gifted Christian teacher and biblical scholar whose immense learning and labors influenced generations of Christian writers. Some of his speculative teachings were later condemned by the Church, and his legacy must therefore be received with discernment rather than treated as an unquestioned standard of Orthodox doctrine.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "A major influence on later Christian theology, though some of his teachings became controversial.",
    "p": 2
  },
  {
    "name": "Cyprian of Carthage",
    "birth_range": [200, 210],
    "death_range": [258, 258],
    "category": ["bishop", "martyr", "writer"],
    "biography": "The holy Bishop and Martyr Cyprian of Carthage, a great shepherd and defender of the unity of the Church, whose writings on the Church, episcopacy, baptism, and martyrdom remain important witnesses to the faith of the ancient Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "One of the most important Latin Christian writers of the third century. Martyred during the persecution under Valerian.",
    "p": 4
  },
  {
    "name": "Novatian",
    "birth_range": [200, 210],
    "death_range": [258, 260],
    "category": ["presbyter", "heretic"],
    "biography": "A Roman presbyter who led a rigorist schism by refusing the Church's merciful restoration of Christians who had fallen during persecution. His schism divided Christians and opposed the Church's authority to receive the repentant back into communion.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The Novatianist movement was schismatic and rigorist; Novatian is not normally classified simply as a doctrinal heretic.",
    "p": 4
  },
  {
    "name": "Dionysius of Alexandria",
    "birth_range": [185, 195],
    "death_range": [264, 265],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Alexandria and former student of Origen who became one of the most important theological leaders of the mid-third century.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Known through surviving fragments and extensive references in later writers.",
    "p": 2
  },
  {
    "name": "Gregory Thaumaturgus",
    "birth_range": [205, 215],
    "death_range": [270, 275],
    "category": ["bishop", "wonderworker", "writer"],
    "biography": "The holy Gregory, Bishop of Neocaesarea and disciple of Origen, who labored greatly to establish and strengthen the Church in Pontus. The Church remembers him as a wonderworker and faithful shepherd.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally associated with numerous miracles and a dramatic expansion of Christianity in his region.",
    "p": 3
  },
  {
    "name": "Firmilian of Caesarea",
    "birth_range": [200, 210],
    "death_range": [268, 269],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Caesarea in Cappadocia and an ally of Cyprian in disputes concerning baptism and ecclesiastical authority.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His surviving correspondence provides important evidence for the organization of third-century Christianity.",
    "p": 5
  },
  {
    "name": "Archelaus of Cascar",
    "birth_range": [220, 230],
    "death_range": [280, 290],
    "category": ["bishop", "writer"],
    "biography": "An Eastern Christian bishop who defended the faith against the teachings of Mani and the errors of Manichaeism, bearing witness to the Church's rejection of its radical dualism.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "Known chiefly through accounts of his disputation with Mani.",
    "p": 5
  },
  {
    "name": "Mani",
    "birth_range": [216, 216],
    "death_range": [274, 277],
    "category": ["religious_teacher", "founder_of_religious_movement", "heretic"],
    "biography": "The founder of Manichaeism, a grave heresy that combined elements borrowed from Christianity with radically dualistic teachings opposed to the Christian revelation of the one God, the Creator of all things, and the true Incarnation of the Son of God.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "Manichaeism is regarded by the Church as a heretical religious movement incorporating Christian elements into a radically dualistic system.",
    "p": 5
  },
  {
    "name": "Bardaisan of Edessa",
    "birth_range": [154, 155],
    "death_range": [222, 223],
    "category": ["writer", "teacher"],
    "biography": "A Syriac Christian teacher and writer associated with the Church of Edessa. Although he was at first regarded as a Christian teacher, later accounts associate his teaching with serious heterodox tendencies, and his precise place in the history of Syriac Christianity remains difficult to define.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His precise theological position is debated. Later writers sometimes associate him with heterodox teachings, but he is not as straightforward a case as Mani or Marcion.",
    "p": 5
  },
  {
    "name": "Julius Africanus",
    "birth_range": [160, 170],
    "death_range": [240, 245],
    "category": ["writer", "chronographer"],
    "biography": "Christian chronographer whose work attempted to construct a universal history incorporating biblical and secular chronology.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "An important early Christian figure in the development of universal Christian historical chronology.",
    "p": 4
  },
  {
    "name": "Minucius Felix",
    "birth_range": [150, 170],
    "death_range": [200, 220],
    "category": ["apologist", "writer"],
    "biography": "Latin Christian apologist traditionally associated with the dialogue Octavius, one of the earliest surviving Latin defenses of Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "His exact dates are uncertain.",
    "p": 5
  },
  {
    "name": "Commodianus",
    "birth_range": [180, 200],
    "death_range": [250, 270],
    "category": ["poet", "writer", "apologist"],
    "biography": "Early Latin Christian poet whose surviving works provide an unusual glimpse into popular Christian apologetic and eschatological thought.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The dating and biography of Commodianus are uncertain.",
    "p": 5
  },
  {
    "name": "Arnobius of Sicca",
    "birth_range": [250, 260],
    "death_range": [327, 330],
    "category": ["apologist", "teacher", "writer"],
    "biography": "North African Christian apologist who defended Christianity against pagan criticism during the transition from the third to the fourth century.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His major work was written shortly before or around the beginning of the Constantinian period.",
    "p": 5
  },
  {
    "name": "Lactantius",
    "birth_range": [250, 260],
    "death_range": [325, 330],
    "category": ["apologist", "writer", "teacher"],
    "biography": "Christian rhetorician and apologist whose writings helped transmit Christian ideas into the Latin literary world during the age of Constantine.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His major literary activity spans the end of the pre-Nicene period and the beginning of the Constantinian era.",
    "p": 3
  },
  {
    "name": "Peter of Alexandria",
    "birth_range": [245, 255],
    "death_range": [311, 311],
    "category": ["bishop", "writer", "martyr"],
    "biography": "The holy Bishop and Martyr Peter of Alexandria, a shepherd of the Church who suffered during the Great Persecution and was martyred for Christ shortly before the Council of Nicaea. He also played an important role in the controversies surrounding the Meletian schism.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His death falls just before the Council of Nicaea.",
    "p": 4
  },
  {
    "name": "Methodius of Olympus",
    "birth_range": [250, 260],
    "death_range": [311, 312],
    "category": ["bishop", "writer", "martyr"],
    "biography": "A bishop, martyr, and theological writer who defended the Church's faith against teachings he regarded as erroneous, including aspects of Origen's speculative theology.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His exact episcopal see and death circumstances are debated.",
    "p": 5
  },
  {
    "name": "Lucian of Antioch",
    "birth_range": [235, 245],
    "death_range": [312, 312],
    "category": ["teacher", "martyr", "writer"],
    "biography": "A Christian teacher and martyr associated with Antioch, remembered for his learning, his service to the Church, and his suffering for Christ under persecution.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally martyred under Maximinus Daia.",
    "p": 5
  },
  {
    "name": "Meletius of Lycopolis",
    "birth_range": [250, 260],
    "death_range": [325, 330],
    "category": ["bishop", "heretic"],
    "biography": "An Egyptian bishop whose rigorist refusal to accept the Church's restoration of clergy who had fallen during persecution led to the Meletian schism, a serious division that continued into the time of the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His movement was schismatic rather than straightforwardly doctrinally heretical.",
    "p": 5
  },

  {
    "name": "Athanasius of Alexandria",
    "birth_range": [295, 298],
    "death_range": [373, 373],
    "category": ["bishop", "writer", "confessor", "saint"],
    "biography": "The holy Athanasius the Great, deacon and secretary to Bishop Alexander of Alexandria at the Council of Nicaea and later Bishop of Alexandria. He was the great defender of the Nicene confession and of the truth that the Son is truly God, consubstantial with the Father, enduring exile and persecution rather than compromise the apostolic faith.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "A central figure in the Nicene controversy and one of the most important theologians of the fourth-century Church.",
    "p": 2
  },
  {
    "name": "Anthony the Great",
    "birth_range": [251, 251],
    "death_range": [356, 356],
    "category": ["monk"],
    "biography": "The holy Anthony the Great, father of the desert and one of the great founders of Christian monasticism. He embraced the ascetic life for love of Christ, became a model of prayer and spiritual warfare, and gathered many disciples who sought salvation under his guidance.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His life, written by Athanasius, became enormously influential in spreading the ideal of Christian monasticism.",
    "p": 3
  },
  {
    "name": "Alexander of Alexandria",
    "birth_range": [250, 260],
    "death_range": [326, 328],
    "category": ["bishop", "writer", "saint"],
    "biography": "The holy Alexander, Archbishop of Alexandria, who steadfastly defended the apostolic faith against the blasphemous teaching of Arius and helped prepare the way for the Council of Nicaea. The deacon Athanasius served under him and became his great successor in the defense of Orthodoxy.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Athanasius served as his deacon and secretary.",
    "p": 3
  },
  {
    "name": "Arius",
    "birth_range": [250, 260],
    "death_range": [336, 336],
    "category": ["presbyter", "writer", "heretic"],
    "biography": "An Alexandrian presbyter whose teaching that the Son of God was a created being denied the true divinity and eternal Sonship of Christ. His teaching, known as Arianism, caused immense division and harm in the Church and was condemned by the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The Nicene Council condemned his teaching; later forms of Arianism continued to influence parts of the Roman Empire.",
    "p": 2
  },
  {
    "name": "Hosius of Corduba",
    "birth_range": [256, 257],
    "death_range": [357, 359],
    "category": ["bishop", "confessor"],
    "biography": "Spanish bishop and influential adviser to Constantine who played a major role in the organization of the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "One of the most important ecclesiastical leaders of the Nicene generation.",
    "p": 5
  },
  {
    "name": "Eusebius of Caesarea",
    "birth_range": [260, 265],
    "death_range": [339, 340],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Caesarea and author of the first major surviving history of the Church. He preserved much valuable testimony concerning the early Christians, though his position amid the Arian controversy was complex and must be understood in the context of the struggles surrounding the Nicene faith.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His theological position during the Arian controversy was complex, but he was not a simple representative of the later Arian movement.",
    "p": 4
  },
  {
    "name": "Eusebius of Nicomedia",
    "birth_range": [260, 270],
    "death_range": [341, 342],
    "category": ["bishop", "writer"],
    "biography": "A powerful fourth-century bishop who became a leading supporter of Arius and a persistent opponent of the Nicene confession. Through ecclesiastical and imperial influence he contributed greatly to the continued turmoil that afflicted the Church after Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His precise theological classification is complicated by the diversity of positions within the anti-Nicene movement, but he is generally associated with the Arian cause.",
    "p": 3
  },
  {
    "name": "Pachomius the Great",
    "birth_range": [292, 298],
    "death_range": [346, 348],
    "category": ["monk"],
    "biography": "The holy Pachomius the Great, father of cenobitic monasticism, who gathered monks into ordered communities devoted to prayer, ascetic labor, obedience, and the common life in Christ.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His communities helped transform monasticism from a collection of solitary ascetics into organized communal institutions.",
    "p": 3
  },
  {
    "name": "Macarius of Egypt",
    "birth_range": [295, 305],
    "death_range": [390, 391],
    "category": ["monk"],
    "biography": "The holy Macarius of Egypt, one of the great fathers of the Egyptian desert and a model of the eremitic life, remembered for profound asceticism, prayer, and spiritual wisdom.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "medium",
    "notes": "Some traditions and writings associated with the name Macarius are difficult to assign with certainty to the historical individual.",
    "p": 3
  },
  {
    "name": "Paphnutius of Thebes",
    "birth_range": [250, 270],
    "death_range": [350, 360],
    "category": ["bishop", "confessor", "monk"],
    "biography": "An Egyptian bishop and confessor who suffered grievously during the Great Persecution and became a revered witness of the Nicene generation.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The details of his life are partly preserved through later tradition.",
    "p": 4
  },
  {
    "name": "Spyridon of Trimythous",
    "birth_range": [250, 270],
    "death_range": [348, 350],
    "category": ["bishop", "confessor"],
    "biography": "The holy Spyridon, Bishop of Trimythous, a simple shepherd who became a faithful bishop and confessor of the Orthodox faith. He is traditionally remembered as a participant in the Council of Nicaea and as a great wonderworker.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "A prominent figure in Orthodox tradition; the details of his biography are heavily shaped by later hagiography.",
    "p": 4
  },
  {
    "name": "James of Nisibis",
    "birth_range": [250, 270],
    "death_range": [338, 350],
    "category": ["bishop", "monk", "ascetic"],
    "biography": "The holy James, Bishop of Nisibis, a great Syriac ascetic and shepherd of the Church, traditionally associated with the Council of Nicaea and remembered as a defender of the faith and a father of the ascetic life.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "An important representative of the eastern and Syriac Christian world.",
    "p": 5
  },
  {
    "name": "Ephrem the Syrian",
    "birth_range": [306, 307],
    "death_range": [373, 373],
    "category": ["deacon", "writer", "poet", "ascetic"],
    "biography": "The holy Ephrem the Syrian, deacon, theologian, poet, and hymnographer, whose writings and hymns became a great treasure of the spiritual and liturgical life of Syriac Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His life and work connect the Nicene era with the flourishing of fourth-century Christian theology and hymnography.",
    "p": 2
  },
  {
    "name": "Hilary of Poitiers",
    "birth_range": [310, 320],
    "death_range": [367, 368],
    "category": ["bishop", "writer", "confessor"],
    "biography": "The holy Hilary, Bishop of Poitiers and confessor, a great defender of the Nicene faith in the Latin-speaking Church who endured exile rather than compromise the truth concerning the Son of God.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Often called the 'Athanasius of the West' for his defense of Nicene faith.",
    "p": 4
  },
//  {
//    "name": "Eusebius of Vercelli",
//    "birth_range": [283, 290],
//    "death_range": [371, 371],
//    "category": ["bishop", "confessor"],
//    "biography": "Western bishop who suffered exile for defending the Nicene faith during the Arian controversy.",
//    "date_basis": "historical_tradition",
//    "date_confidence": "medium",
//    "identity_confidence": "high",
//    "notes": "An important representative of the Western Nicene resistance.",
//    "p": 4
//  },
  {
    "name": "Lucifer of Cagliari",
    "birth_range": [290, 300],
    "death_range": [370, 371],
    "category": ["bishop", "confessor", "heretic"],
    "biography": "A Sardinian bishop and fierce defender of the Nicene faith who, through an excessively rigorous response to the restoration of former Arians, became involved in the Luciferian schism and separated himself from the Church's broader reconciliation.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "A useful example of the distinction between doctrinal orthodoxy and later schism.",
    "p": 5
  },

  {
    "name": "Photini",
    "birth_range": [0, 20],
    "death_range": [65, 100],
    "category": ["martyr"],
    "biography": "The Samaritan Woman whom Christ met at the well and to whom He revealed Himself as the Messiah. The Church traditionally calls her Photini and remembers her as an apostolic missionary and martyr who proclaimed Christ after her encounter with Him.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "historicity": "traditional",
    "notes": "The Gospel identifies the woman but does not give her name; Photini is the traditional name in Eastern Christianity.",
    "p": 4
  },
  {
    "name": "Longinus",
    "birth_range": [0, 20],
    "death_range": [30, 100],
    "category": ["soldier", "martyr"],
    "biography": "The soldier traditionally associated with the Crucifixion who, after witnessing the death of Christ, confessed the truth of what he had seen. The Church remembers him as a martyr for Christ.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The Gospel of John does not name the soldier who pierced Christ's side; Longinus is the later traditional identification.",
    "p": 4
  },
  {
    "name": "Stephen",
    "birth_range": [0, 10],
    "death_range": [34, 37],
    "category": ["deacon", "martyr"],
    "biography": "The holy Protomartyr and Archdeacon Stephen, one of the Seven appointed to serve the Church in Jerusalem and the first Christian martyr recorded in the New Testament. He bore witness to Christ and was stoned while praying for his persecutors.",
    "date_basis": "traditional_estimate",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "His martyrdom is narrated in Acts 6–7.",
    "p": 3
  },
  {
    "name": "Perpetua",
    "birth_range": [180, 185],
    "death_range": [203, 203],
    "category": ["martyr", "noblewoman"],
    "biography": "The holy Martyr Perpetua, a young Christian woman of noble birth who steadfastly confessed Christ and suffered martyrdom at Carthage during the persecution of Septimius Severus.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Martyred at Carthage during the persecution of Septimius Severus.",
    "p": 3
  },
//  {
//    "name": "Speratus",
//    "birth_range": [150, 175],
//    "death_range": [180, 203],
//    "category": ["martyr"],
//    "biography": "Leader among the Scillitan Martyrs, among the earliest securely documented Christian martyrs in Roman North Africa.",
//    "date_basis": "historical",
//    "date_confidence": "medium",
//    "identity_confidence": "high",
//    "historicity": "historical",
//  //  "notes": "The Scillitan Martyrs were executed in 180.",
//    "p": 5
//  },
  {
    "name": "Pothinus of Lyons",
    "birth_range": [80, 90],
    "death_range": [177, 177],
    "category": ["bishop", "martyr", "missionary"],
    "biography": "The holy Pothinus, first Bishop of Lyons and a missionary bishop who led the Christian community during the persecution of 177 and received the crown of martyrdom for Christ.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Among the earliest known bishops and martyrs of the Church in Gaul.",
    "p": 2
  },
  {
    "name": "Thecla",
    "birth_range": [20, 40],
    "death_range": [80, 100],
    "category": ["missionary", "ascetic", "martyr", "traditional_figure"],
    "biography": "The holy Protomartyr and Equal-to-the-Apostles Thecla, a disciple of the Apostle Paul who forsook the world for Christ and became a model of virginity, ascetic devotion, and missionary zeal.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "historicity": "traditional",
    "notes": "The Acts of Paul and Thecla is an early Christian text, but the details of her biography are difficult to establish historically.",
    "p": 5
  },
  {
    "name": "Nicholas of Myra",
    "birth_range": [270, 290],
    "death_range": [343, 350],
    "category": ["bishop", "confessor"],
    "biography": "The holy Nicholas, Archbishop of Myra, a merciful shepherd of the Church who became renowned for his love of the poor, pastoral charity, and steadfast confession of Christ. He is one of the most beloved saints of the Christian world.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "A historical bishop probably existed, but the details of the familiar biography are heavily shaped by later tradition.",
    "p": 2
  },
  {
    "name": "Sebastian of Rome",
    "birth_range": [250, 270],
    "death_range": [288, 305],
    "category": ["soldier", "martyr"],
    "biography": "The holy Martyr Sebastian, traditionally remembered as a Christian soldier who strengthened and encouraged persecuted believers and suffered martyrdom for his confession of Christ.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "A highly influential martyr in later Christian devotion, though the details of his biography are uncertain.",
    "p": 4
  },
  {
    "name": "St. George",
    "birth_range": [270, 285],
    "death_range": [303, 305],
    "category": ["soldier", "martyr"],
    "biography": "The holy Great-martyr George, a soldier who boldly confessed Christ and suffered martyrdom during the persecutions. He is one of the most widely venerated saints of the Church and a great example of courage and faithfulness.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "p": 3
  },
  {
    "name": "Victor of Marseilles",
    "birth_range": [230, 260],
    "death_range": [303, 304],
    "category": ["soldier", "martyr"],
    "biography": "The holy Martyr Victor, a Christian soldier who refused to deny Christ and suffered martyrdom at Marseilles during the Great Persecution.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "A representative of the many military martyrs remembered from the Great Persecution.",
    "p": 5
  },
//  {
//    "name": "Maurice of the Theban Legion",
//    "birth_range": [250, 270],
//    "death_range": [285, 305],
//    "category": ["soldier", "martyr"],
//    "biography": "Traditional commander of the Theban Legion, remembered as a Christian soldier who refused to participate in persecution and was martyred with his companions.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "The historical details of the Theban Legion account are debated.",
//    "p": 5
//  },
  {
    "name": "Lucy of Syracuse",
    "birth_range": [280, 290],
    "death_range": [304, 304],
    "category": ["martyr", "virgin"],
    "biography": "The holy Virgin-martyr Lucy of Syracuse, who consecrated herself to Christ and steadfastly endured persecution and death rather than deny her Lord.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "One of the most widely venerated female martyrs of late antiquity.",
    "p": 4
  },
  {
    "name": "Catherine of Alexandria",
    "birth_range": [280, 290],
    "death_range": [305, 320],
    "category": ["martyr", "virgin"],
    "biography": "The holy Great-martyr Catherine of Alexandria, a virgin of great wisdom who confessed Christ before pagan authority and suffered martyrdom rather than renounce the true faith.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "One of the most prominent traditional female martyrs of the Great Persecution.",
    "p": 3
  },

  {
    "name": "St. Dmitri",
    "birth_range": [270, 285],
    "death_range": [303, 306],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Demetrius of Thessalonica, a soldier and faithful servant of Christ who confessed the Gospel and suffered martyrdom. He is one of the great military saints and wonderworkers of the Christian East.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "His traditional commemoration is closely associated with the persecution under Maximian; the details of his biography are difficult to establish independently.",
    "p": 3
  },
//  {
//    "name": "Nestor of Thessalonica",
//    "birth_range": [280, 295],
//    "death_range": [303, 306],
//    "category": ["martyr", "young_martyr"],
//    "biography": "Young man traditionally instructed and encouraged by Demetrius, who defeated the pagan champion Lyaios before being martyred.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "medium",
//    "historicity": "traditional_historical",
//    "notes": "The traditional account explicitly presents him as a disciple or spiritual protégé of Demetrius.",
//    "p": 5
//  },
  {
    "name": "Theodore the Recruit",
    "birth_range": [270, 285],
    "death_range": [306, 306],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Theodore the Recruit, a Christian soldier who refused to sacrifice to pagan gods and suffered martyrdom at Euchaita rather than deny Christ.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "Also known as Theodore Tiro or Theodore the Recruit.",
    "p": 5
  },
  {
    "name": "Theodore Stratelates",
    "birth_range": [270, 285],
    "death_range": [319, 319],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Theodore Stratelates, a military commander who boldly confessed Christ and suffered martyrdom for the faith.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The relationship between the traditions of Theodore Stratelates and Theodore the Recruit is historically complicated.",
    "p": 5
  },
  {
    "name": "Menas of Egypt",
    "birth_range": [270, 285],
    "death_range": [304, 310],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Menas of Egypt, a Christian soldier who renounced the service of the pagan empire and suffered martyrdom rather than deny Christ. He is one of the most widely venerated military martyrs of the Christian East.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "One of the most widely venerated military martyrs of Egypt and the Christian East.",
    "p": 4
  },
  {
    "name": "Mercurius of Caesarea",
    "birth_range": [220, 250],
    "death_range": [250, 270],
    "category": ["soldier", "martyr"],
    "biography": "The holy Great-martyr Mercurius, a Christian soldier who suffered martyrdom for Christ and became one of the most beloved military saints of the Christian East.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The chronology of the different traditions associated with Mercurius is uncertain.",
    "p": 3
  },

//  {
//    "name": "Anastasia of Sirmium",
//    "birth_range": [270, 285],
//    "death_range": [304, 305],
//    "category": ["martyr", "great_martyr"],
//    "biography": "Christian woman traditionally martyred during the Great Persecution and remembered for ministering to imprisoned Christians.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "medium",
//    "historicity": "traditional_historical",
//  //  "notes": "One of the most important female martyrs of the late Roman persecutions.",
//    "p": 5
//  },
  {
    "name": "Barbara of Heliopolis",
    "birth_range": [270, 290],
    "death_range": [305, 320],
    "category": ["virgin", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Barbara, a virgin who confessed Christ despite the opposition of her father and suffered martyrdom rather than renounce the true faith.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "One of the most prominent traditional female martyrs of the Great Persecution.",
    "p": 4
  },
  {
    "name": "Marina of Antioch",
    "birth_range": [270, 290],
    "death_range": [304, 320],
    "category": ["virgin", "martyr", "great_martyr"],
    "biography": "The holy Great-martyr Marina of Antioch, a virgin who steadfastly confessed Christ and suffered martyrdom for His sake. In the West she is known as Margaret of Antioch.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "Known in the West as Margaret of Antioch; the historical basis of the developed legend is uncertain.",
    "p": 4
  },
  {
    "name": "Irene of Thessalonica",
    "birth_range": [270, 290],
    "death_range": [304, 305],
    "category": ["virgin", "martyr"],
    "biography": "The holy Virgin-martyr Irene of Thessalonica, who confessed Christ and suffered martyrdom during the persecutions, traditionally remembered together with her sisters Agape and Chionia.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "Often remembered together with her sisters Agape and Chionia.",
    "p": 4
  },
//  {
//    "name": "Mariamne",
//    "birth_range": [0, 20],
//    "death_range": [50, 100],
//    "category": ["missionary"],
//    "biography": "Traditional sister of the Apostle Philip and missionary associated with the early spread of the Gospel.",
//    "date_basis": "tradition",
//    "date_confidence": "very_low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "A significant traditional female missionary of the apostolic age.",
//    "p": 5
//  },
//  {
//    "name": "Domnina",
//    "birth_range": [20, 50],
//    "death_range": [65, 100],
//    "category": ["martyr"],
//    "biography": "Traditional daughter of the Emperor Nero who is remembered as a convert to Christianity and companion of Photini in martyrdom.",
//    "date_basis": "tradition",
//    "date_confidence": "very_low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "Part of the traditional Photini martyr cycle.",
//    "p": 5
//  },
];
