const people = [
  {
    "name": "Jesus Christ",
    "birth_range": [-4, 0],
    "death_range": [29, 33],
    "category": ["son_of_god", "martyr"],
    "biography": "Our Lord and God and Savior",
    "image": "jesus_christ.jpg",
    "date_basis": "traditional",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "",
    "p": 0,
  },
  {
    "name": "Mary the Theotokos",
    "birth_range": [-25, -15],
    "death_range": [40, 60],
    "category": ["mother_of_god"],
    "biography": "Virgin mother of Jesus and central figure in the apostolic community after the Resurrection.",
    "image": "theotokos.jpg",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "The New Testament does not give a date of death; later traditions differ.",
    "p": 1
  },
  {
    "name": "John the Baptist",
    "birth_range": [-4, 0],
    "death_range": [26, 30],
    "category": ["prophet", "martyr", "missionary"],
    "biography": "The forerunner and baptist of the Lord.",
    "date_basis": "traditional",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "",
    "p": 1,
  },
  {
    "name": "Peter",
    "birth_range": [1, 10],
    "death_range": [64, 67],
    "category": ["apostle", "bishop", "martyr"],
    "biography": "One of the Twelve and a leading apostolic witness; traditionally the first bishop of Antioch and later bishop of Rome.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The traditional date of martyrdom under Nero is approximately 64–67.",
    "p": 1
  },
  {
    "name": "John",
    "birth_range": [5, 15],
    "death_range": [95, 100],
    "category": ["apostle", "evangelist", "writer", "bishop"],
    "biography": "One of the Twelve and traditionally the author of the Fourth Gospel, three epistles, and Revelation; associated with the churches of Asia Minor.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Tradition places his death during the reign of Trajan, commonly around 98–100.",
    "p": 1
  },
  {
    "name": "James the brother of the Lord",
    "birth_range": [-10, 10],
    "death_range": [62, 62],
    "category": ["bishop", "martyr"],
    "biography": "Leader of the Jerusalem church and a central figure in the earliest Christian community.  James was not a biological brother, but either a step-brother or a cousin.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "His death in Jerusalem is reported by Josephus and other early sources.",
    "p": 1
  },
  {
    "name": "Paul",
    "birth_range": [5, 10],
    "death_range": [64, 67],
    "category": ["apostle", "missionary", "writer", "martyr"],
    "biography": "Apostle to the Gentiles and principal missionary of the first Christian generation; author of many New Testament letters.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally martyred in Rome under Nero.",
    "p": 1
  },
  {
    "name": "Matthew",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "evangelist", "writer", "missionary", "martyr"],
    "biography": "One of the Twelve; traditionally associated with the Gospel of Matthew and missionary work beyond Palestine.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The location and date of his death are uncertain.",
    "p": 1
  },
  {
    "name": "Luke",
    "birth_range": [5, 15],
    "death_range": [80, 90],
    "category": ["evangelist", "writer", "missionary", "martyr"],
    "biography": "Companion of Paul and traditional author of the Gospel of Luke and Acts.",
    "date_basis": "traditional",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "The traditional date of death is often placed around 84.",
    "p": 1
  },
  {
    "name": "Mark",
    "birth_range": [5, 15],
    "death_range": [65, 80],
    "category": ["evangelist", "writer", "missionary", "bishop", "martyr"],
    "biography": "Early missionary associated with Peter and Paul and traditionally the author of the Gospel of Mark; regarded as founder of the church of Alexandria.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The identification of Mark with John Mark is traditional and widely accepted.",
    "p": 1
  },
  {
    "name": "Andrew",
    "birth_range": [-5, 5],
    "death_range": [60, 70],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve and brother of Peter; later tradition associates him with missionary work around the Black Sea and Greece.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Traditional accounts of his later missionary activity and martyrdom vary.",
    "p": 2
  },
  {
    "name": "Thomas",
    "birth_range": [1, 10],
    "death_range": [65, 75],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve; ancient tradition strongly associates him with the evangelization of Mesopotamia and India.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The tradition of his Indian mission is ancient, though details are difficult to verify.",
    "p": 2
  },
  {
    "name": "Philip",
    "birth_range": [1, 15],
    "death_range": [70, 90],
    "category": ["apostle", "missionary"],
    "biography": "One of the Twelve; associated in early tradition with missionary work in Asia Minor.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Some traditions may conflate him with Philip the evangelist.",
    "p": 2
  },
  {
    "name": "Bartholomew",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve; later traditions associate him with missions in Armenia, India, and other eastern regions.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "The details of his later life and death are highly uncertain.",
    "p": 2
  },
  {
    "name": "James son of Alphaeus",
    "birth_range": [1, 15],
    "death_range": [50, 100],
    "category": ["apostle", "missionary"],
    "biography": "One of the Twelve; little is securely known about his later life.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "Later traditions about his ministry and death vary considerably.",
    "p": 2
  },
  {
    "name": "James son of Zebedee",
    "birth_range": [-5, 5],
    "death_range": [42, 44],
    "category": ["apostle", "martyr"],
    "biography": "One of the Twelve and brother of John, traditionally regarded as the first of the Twelve to be martyred.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Acts 12 records his execution by Herod Agrippa I.",
    "p": 2
  },
  {
    "name": "Jude / Thaddeus",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve; associated by tradition with missionary work in Syria and Mesopotamia.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The identification of various New Testament figures named Jude or Judas is complex.",
    "p": 2
  },
  {
    "name": "Simon the Zealot",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "One of the Twelve; later traditions assign him missionary activity in various regions.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "His later life is poorly documented.",
    "p": 2
  },
  {
    "name": "Ignatius of Antioch",
    "birth_range": [35, 50],
    "death_range": [107, 117],
    "category": ["bishop", "martyr", "writer"],
    "biography": "Bishop of Antioch who wrote seven major letters while being taken to Rome for martyrdom.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "One of the most important witnesses to early second-century Christianity.",
    "p": 2
  },
  {
    "name": "Matthias",
    "birth_range": [1, 15],
    "death_range": [60, 100],
    "category": ["apostle", "missionary", "martyr"],
    "biography": "Chosen to replace Judas Iscariot among the Twelve after the Resurrection.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "Later traditions concerning his mission and death vary.",
    "p": 4
  },
  {
    "name": "Barnabas",
    "birth_range": [5, 10],
    "death_range": [60, 70],
    "category": ["missionary"],
    "biography": "Levite from Cyprus and Paul's early missionary partner; a major evangelist of the first generation.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Later traditions associate him strongly with Cyprus.",
    "p": 4
  },
  {
    "name": "Linus",
    "birth_range": [10, 20],
    "death_range": [76, 80],
    "category": ["bishop"],
    "biography": "Traditionally the first bishop of Rome after Peter.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Named in 2 Timothy 4:21 and early Roman succession lists.",
    "p": 3
  },
  {
    "name": "Anacletus / Cletus",
    "birth_range": [20, 30],
    "death_range": [88, 92],
    "category": ["bishop"],
    "biography": "Traditionally the second bishop of Rome after Linus.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "Ancient sources differ over whether Anacletus and Cletus were the same person.",
    "p": 4
  },
  {
    "name": "Clement of Rome",
    "birth_range": [35, 45],
    "death_range": [100, 102],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Rome and author of 1 Clement, one of the earliest surviving post-New Testament Christian writings.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally associated with the third position in the Roman succession after Peter.",
    "p": 3
  },
  {
    "name": "Evodius of Antioch",
    "birth_range": [20, 30],
    "death_range": [66, 69],
    "category": ["bishop"],
    "biography": "Traditionally the first bishop of Antioch after Peter and an early leader of the Syrian church.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The exact chronology of the Antiochene succession is uncertain.",
    "p": 4
  },
  {
    "name": "Hero of Antioch",
    "birth_range": [60, 70],
    "death_range": [120, 140],
    "category": ["bishop"],
    "biography": "Traditionally the successor of Ignatius as bishop of Antioch.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "Little securely known.",
    "p": 4
  },
  {
    "name": "Simeon of Jerusalem",
    "birth_range": [1, 10],
    "death_range": [107, 117],
    "category": ["bishop", "martyr"],
    "biography": "Relative of Jesus and successor to James as leader of the Jerusalem church; traditionally martyred under Trajan.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Eusebius preserves traditions concerning his succession and martyrdom.",
    "p": 4
  },
  {
    "name": "Polycarp of Smyrna",
    "birth_range": [65, 75],
    "death_range": [155, 160],
    "category": ["bishop", "martyr", "writer"],
    "biography": "Bishop of Smyrna and traditional disciple of John; martyred at an advanced age.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His connection with John is reported by Irenaeus.",
    "p": 2
  },
  {
    "name": "Papias of Hierapolis",
    "birth_range": [60, 70],
    "death_range": [130, 140],
    "category": ["bishop", "writer"],
    "biography": "Bishop who collected traditions from those who had known the apostles and wrote an early exposition of the sayings of Jesus.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His work survives only in fragments quoted by later authors.",
    "p": 4
  },
  {
    "name": "Quadratus of Athens",
    "birth_range": [70, 80],
    "death_range": [125, 140],
    "category": ["writer", "bishop"],
    "biography": "Early Christian apologist who presented a defense of Christianity to Emperor Hadrian.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Often regarded as one of the earliest named Christian apologists.",
    "p": 4
  },
  {
    "name": "Aristides of Athens",
    "birth_range": [75, 85],
    "death_range": [125, 150],
    "category": ["writer", "philosopher"],
    "biography": "Christian philosopher and apologist who defended Christianity before the emperor.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The details of his life are sparse.",
    "p": 4
  },
  {
    "name": "Hermas",
    "birth_range": [70, 80],
    "death_range": [140, 150],
    "category": ["writer", "prophet"],
    "biography": "Roman Christian associated with the Shepherd of Hermas, an influential early Christian prophetic work.",
    "date_basis": "early_historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The work itself is better attested than the author's biography.",
    "p": 2
  },
  {
    "name": "Justin Martyr",
    "birth_range": [95, 105],
    "death_range": [165, 167],
    "category": ["writer", "philosopher", "martyr"],
    "biography": "Christian philosopher and apologist whose writings describe Christian worship and belief in the mid-second century.",
    "date_basis": "historical",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His martyrdom under Marcus Aurelius is well established.",
    "p": 2
  },
  {
    "name": "Irenaeus of Lyons",
    "birth_range": [130, 140],
    "death_range": [195, 205],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Lyons and major defender of apostolic succession and the rule of faith against Gnosticism.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "He personally knew Polycarp as a young man.",
    "p": 2
  },
  {
    "name": "Hegesippus",
    "birth_range": [110, 120],
    "death_range": [175, 185],
    "category": ["writer"],
    "biography": "Early Christian historian who traveled among churches and collected traditions concerning the apostolic age.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings survive only in fragments.",
    "p": 3
  },
  {
    "name": "Aquila",
    "birth_range": [10, 20],
    "death_range": [60, 80],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Jewish Christian missionary and co-worker of Paul, together with his wife Priscilla.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Mentioned repeatedly in the Pauline letters and Acts.",
    "p": 4
  },
  {
    "name": "Priscilla",
    "birth_range": [10, 20],
    "death_range": [60, 80],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Important missionary and teacher in the Pauline churches, working alongside Aquila.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "One of the most prominent women in the earliest Christian missionary movement.",
    "p": 4
  },
  {
    "name": "Silas / Silvanus",
    "birth_range": [10, 20],
    "death_range": [60, 75],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Missionary companion of Paul and important early Christian messenger.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The identification of Silas with Silvanus is traditional and widely accepted.",
    "p": 4
  },
  {
    "name": "Titus",
    "birth_range": [10, 20],
    "death_range": [90, 100],
    "category": ["missionary", "bishop", "apostolic_worker"],
    "biography": "Trusted co-worker of Paul and traditionally the first bishop of Crete.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His later episcopal role is primarily preserved in tradition.",
    "p": 4
  },
  {
    "name": "Timothy",
    "birth_range": [20, 30],
    "death_range": [90, 100],
    "category": ["missionary", "bishop", "apostolic_worker"],
    "biography": "Close co-worker of Paul and traditionally the first bishop of Ephesus.",
    "date_basis": "traditional",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "The New Testament gives substantial information about his relationship with Paul.",
    "p": 4
  },
  {
    "name": "Tychicus",
    "birth_range": [20, 30],
    "death_range": [70, 90],
    "category": ["missionary", "apostolic_worker"],
    "biography": "Pauline co-worker and messenger associated with several apostolic letters.",
    "date_basis": "historical_tradition",
    "date_confidence": "very_low",
    "identity_confidence": "high",
    "notes": "His later life is unknown.",
    "p": 5
  },
  {
    "name": "Onesimus",
    "birth_range": [30, 40],
    "death_range": [90, 110],
    "category": ["missionary", "bishop", "apostolic_worker"],
    "biography": "Traditionally identified with the person mentioned by Paul in Philemon and later associated with the church of Ephesus.",
    "date_basis": "traditional",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The identification of the Onesimus of Philemon with the later bishop is traditional but not certain.",
    "p": 4
  },
  {
    "name": "Dionysius the Areopagite",
    "birth_range": [10, 20],
    "death_range": [80, 100],
    "category": ["missionary", "bishop"],
    "biography": "Athenian convert mentioned in Acts; later traditions associate him with early Christian leadership in Athens.",
    "date_basis": "mixed_historical_tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "notes": "The later biography is difficult to distinguish from subsequent legendary development.",
    "p": 4
  },
  {
    "name": "Pantaenus",
    "birth_range": [100, 110],
    "death_range": [190, 210],
    "category": ["missionary", "writer"],
    "biography": "Leading figure in the Alexandrian catechetical tradition and missionary to the East.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Associated with the early development of Christian intellectual life in Alexandria.",
    "p": 4
  },
  {
    "name": "Theophilus of Antioch",
    "birth_range": [115, 125],
    "death_range": [180, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop and early Christian apologist who wrote for a pagan intellectual audience.",
    "date_basis": "historical",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Active in the later second century.",
    "p": 4
  },

  {
    "name": "Athenagoras of Athens",
    "birth_range": [125, 135],
    "death_range": [185, 195],
    "category": ["philosopher", "writer"],
    "biography": "Christian philosopher and apologist who wrote a sophisticated defense of Christianity for the pagan intellectual world.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Author of the Plea for the Christians and a work on the resurrection of the dead; his dates are approximate.",
    "p": 4
  },
  {
    "name": "Tatian the Syrian",
    "birth_range": [110, 120],
    "death_range": [170, 180],
    "category": ["writer"],
    "biography": "Syrian Christian intellectual and student of Justin Martyr; author of the Diatessaron, an early harmony of the four Gospels.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Later associated with Encratite tendencies, but his earlier work represents an important stage in the development of Christian literary culture.",
    "p": 4
  },
  {
    "name": "Melito of Sardis",
    "birth_range": [95, 105],
    "death_range": [180, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Sardis and influential Christian writer whose surviving Paschal homily is one of the earliest substantial examples of Christian theological preaching.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "An important witness to second-century theology, especially concerning Christ and Pascha.",
    "p": 3
  },
  {
    "name": "Dionysius of Corinth",
    "birth_range": [100, 110],
    "death_range": [170, 180],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Corinth whose letters to churches across the Christian world demonstrate communication and mutual awareness among distant Christian communities.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings survive only in fragments, but Eusebius regarded him as an important second-century church leader.",
    "p": 4
  },
  {
    "name": "Apollinaris of Hierapolis",
    "birth_range": [120, 130],
    "death_range": [175, 190],
    "category": ["bishop", "writer"],
    "biography": "Bishop and Christian apologist who wrote against paganism and defended the Christian faith during the reign of Marcus Aurelius.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His writings are largely lost but he was regarded as a significant early Christian author.",
    "p": 5
  },
  {
    "name": "Polycrates of Ephesus",
    "birth_range": [125, 135],
    "death_range": [195, 205],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Ephesus who defended the Asian Christian tradition concerning the date of Pascha in correspondence with Rome.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Represents the continuing strength of the Johannine churches in Asia Minor.",
    "p": 5
  },
  {
    "name": "Clement of Alexandria",
    "birth_range": [145, 155],
    "death_range": [215, 220],
    "category": ["writer"],
    "biography": "Major Christian teacher in Alexandria who sought to articulate Christianity in conversation with Greek philosophy and classical learning.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Slightly later than the core apostolic and immediate post-apostolic period, but an important bridge into the mature intellectual tradition of the early Church.",
    "p": 3
  },
  {
    "name": "Abercius of Hierapolis",
    "birth_range": [90, 105],
    "death_range": [170, 200],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Hierapolis associated with an early Christian funerary inscription describing the Christian world as a connected community united by faith and Eucharistic fellowship.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The Abercius inscription is an important early witness to Christian self-understanding and pilgrimage.",
    "p": 5
  },
  {
    "name": "Marcion of Sinope",
    "heretic": true,
    "birth_range": [80, 90],
    "death_range": [150, 160],
    "category": ["teacher", "writer", "heretic"],
    "biography": "Influential second-century Christian teacher whose radical distinction between the God of the Old Testament and the Father of Jesus provoked a major response from the Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Not part of the catholic succession, but historically important for understanding the development of the New Testament canon and orthodox responses to competing interpretations of Christianity.",
    "p": 5
  },
  {
    "name": "Valentinus",
    "heretic": true,
    "birth_range": [95, 105],
    "death_range": [160, 170],
    "category": ["teacher", "writer", "heretic"],
    "biography": "Highly influential gnostic teacher associated with the Valentinian movement.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "Useful for understanding the theological environment against which Irenaeus and other orthodox writers argued.",
    "p": 4
  },
  {
    "name": "Basilides",
    "heretic": true,
    "birth_range": [100, 115],
    "death_range": [140, 160],
    "category": ["teacher", "writer", "heretic"],
    "biography": "Alexandrian Christian teacher associated with an influential Gnostic theological system in the first half of the second century.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His inclusion is useful for showing the diversity of competing Christian interpretations in the second century.",
    "p": 4
  },
  {
    "name": "Ptolemy the Valentinian",
    "heretic": true,
    "birth_range": [100, 120],
    "death_range": [160, 180],
    "category": ["teacher", "writer", "heretic"],
    "biography": "Prominent Valentinian teacher whose surviving Letter to Flora provides an important example of second-century Christian theological interpretation.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "His exact biography is uncertain, but he is an important representative of the Valentinian movement.",
    "p": 5
  },
  {
    "name": "Soter of Rome",
    "birth_range": [100, 110],
    "death_range": [174, 182],
    "category": ["bishop"],
    "biography": "Bishop of Rome in the later second century, remembered for his concern for other churches and his correspondence with the church of Corinth.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "A useful figure for illustrating the growing interconnection of major Christian churches.",
    "p": 5
  },
  {
    "name": "Eleutherus of Rome",
    "birth_range": [110, 120],
    "death_range": [189, 189],
    "category": ["bishop"],
    "biography": "Bishop of Rome during the late second century and a contemporary of Irenaeus.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His episcopate falls near the period when catholic Christian structures and identity were becoming increasingly explicit.",
    "p": 5
  },


  {
    "name": "Tertullian",
    "birth_range": [155, 165],
    "death_range": [220, 225],
    "category": ["apologist", "writer"],
    "biography": "North African Christian lawyer and prolific writer whose Latin theological vocabulary profoundly influenced Western Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
      "notes": "Later associated with Montanism. His major writings belong primarily to the late second and early third centuries; his final ecclesiastical status is historically complicated.",
    "p": 3
  },
  {
    "name": "Hippolytus of Rome",
    "birth_range": [165, 175],
    "death_range": [235, 235],
    "category": ["bishop", "writer", "martyr"],
    "biography": "Major Roman theologian and writer associated with an early liturgical tradition and with opposition to certain Roman bishops.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "medium",
      "notes": "His precise identity and relationship to the Roman episcopate are debated; traditionally died in exile or martyrdom.",
    "p": 2
  },
  {
    "name": "Origen of Alexandria",
    "birth_range": [184, 186],
    "death_range": [253, 254],
    "category": ["biblical_scholar", "teacher", "writer"],
    "biography": "One of the most intellectually influential Christian scholars of antiquity, known for biblical criticism, exegesis, and systematic theological reflection.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
      "notes": "A central figure for understanding the development of Christian biblical scholarship and theology before Nicaea. Some teachings later associated with Origenism were condemned, but the status of Origen himself is historically and ecclesiastically complex.",
    "p": 2
  },
  {
    "name": "Cyprian of Carthage",
    "birth_range": [200, 210],
    "death_range": [258, 258],
    "category": ["bishop", "martyr", "writer"],
    "biography": "Bishop of Carthage whose writings on the Church, episcopacy, baptism, and martyrdom became enormously influential.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
      "notes": "Martyred during the persecution under Valerian.",
    "p": 5
  },
  {
    "name": "Novatian",
    "birth_range": [200, 210],
    "death_range": [258, 260],
    "category": ["writer", "schismatic_leader"],
    "biography": "Roman theologian who led a rigorist schism over the restoration of Christians who had lapsed during persecution.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "The Novatianist movement was schismatic and rigorist; Novatian is not normally classified simply as a doctrinal heretic.",
    "p": 5
  },
  {
    "name": "Dionysius of Alexandria",
    "birth_range": [185, 195],
    "death_range": [264, 265],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Alexandria and former student of Origen who became one of the most important theological leaders of the mid-third century.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Known through surviving fragments and extensive references in later writers.",
    "p": 2
  },
  {
    "name": "Gregory Thaumaturgus",
    "birth_range": [205, 215],
    "death_range": [270, 275],
    "category": ["bishop", "missionary", "writer"],
    "biography": "Bishop of Neocaesarea and student of Origen who helped establish Christianity in Pontus.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Later tradition greatly magnified his miraculous reputation, but his historical missionary importance is substantial.",
    "p": 3
  },
  {
    "name": "Firmilian of Caesarea",
    "birth_range": [200, 210],
    "death_range": [268, 269],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Caesarea in Cappadocia and an ally of Cyprian in disputes concerning baptism and ecclesiastical authority.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His surviving correspondence provides important evidence for the organization of third-century Christianity.",
    "p": 5
  },
  {
    "name": "Archelaus of Cascar",
    "birth_range": [220, 230],
    "death_range": [280, 290],
    "category": ["bishop", "apologist", "writer"],
    "biography": "Eastern Christian bishop known for a recorded disputation against the teachings of Mani.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "Represents the eastern Christian response to emerging Manichaeism.",
    "p": 5
  },
  {
    "name": "Mani",
    "birth_range": [216, 216],
    "death_range": [274, 277],
    "category": ["religious_teacher", "founder_of_religious_movement", "heretic"],
    "biography": "Founder of Manichaeism, a major religious movement that emerged in the third-century Persian world and competed with Christianity across a vast area.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "Manichaeism is regarded by the Church as a heretical religious movement incorporating Christian elements into a radically dualistic system.",
    "p": 5
  },
  {
    "name": "Bardaisan of Edessa",
    "birth_range": [154, 155],
    "death_range": [222, 223],
    "category": ["writer", "teacher"],
    "biography": "Syriac Christian intellectual and writer associated with the church of Edessa and early Syriac Christian literature.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His precise theological position is debated. Later writers sometimes associate him with heterodox teachings, but he is not as straightforward a case as Mani or Marcion.",
    "p": 5
  },
  {
    "name": "Julius Africanus",
    "birth_range": [160, 170],
    "death_range": [240, 245],
    "category": ["writer", "chronographer"],
    "biography": "Christian chronographer whose work attempted to construct a universal history incorporating biblical and secular chronology.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "An important early Christian figure in the development of universal Christian historical chronology.",
    "p": 4
  },
  {
    "name": "Minucius Felix",
    "birth_range": [150, 170],
    "death_range": [200, 220],
    "category": ["apologist", "writer"],
    "biography": "Latin Christian apologist traditionally associated with the dialogue Octavius, one of the earliest surviving Latin defenses of Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "His exact dates are uncertain.",
    "p": 5
  },
  {
    "name": "Commodianus",
    "birth_range": [180, 200],
    "death_range": [250, 270],
    "category": ["poet", "writer", "apologist"],
    "biography": "Early Latin Christian poet whose surviving works provide an unusual glimpse into popular Christian apologetic and eschatological thought.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The dating and biography of Commodianus are uncertain.",
    "p": 5
  },
  {
    "name": "Arnobius of Sicca",
    "birth_range": [250, 260],
    "death_range": [327, 330],
    "category": ["apologist", "teacher", "writer"],
    "biography": "North African Christian apologist who defended Christianity against pagan criticism during the transition from the third to the fourth century.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His major work was written shortly before or around the beginning of the Constantinian period.",
    "p": 5
  },
  {
    "name": "Lactantius",
    "birth_range": [250, 260],
    "death_range": [325, 330],
    "category": ["apologist", "writer", "teacher"],
    "biography": "Christian rhetorician and apologist whose writings helped transmit Christian ideas into the Latin literary world during the age of Constantine.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His major literary activity spans the end of the pre-Nicene period and the beginning of the Constantinian era.",
    "p": 3
  },
  {
    "name": "Peter of Alexandria",
    "birth_range": [245, 255],
    "death_range": [311, 311],
    "category": ["bishop", "writer", "martyr"],
    "biography": "Bishop of Alexandria who was martyred during the persecution of Diocletian and became an important figure in the Meletian controversy.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His death falls just before the Council of Nicaea.",
    "p": 4
  },
  {
    "name": "Methodius of Olympus",
    "birth_range": [250, 260],
    "death_range": [311, 312],
    "category": ["bishop", "writer", "martyr"],
    "biography": "Bishop and theological writer who criticized aspects of Origen's thought while developing his own account of Christian theology.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His exact episcopal see and death circumstances are debated.",
    "p": 5
  },
  {
    "name": "Lucian of Antioch",
    "birth_range": [235, 245],
    "death_range": [312, 312],
    "category": ["teacher", "martyr", "writer"],
    "biography": "Influential biblical scholar and teacher associated with Antioch whose textual and theological legacy influenced later eastern Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Traditionally martyred under Maximinus Daia.",
    "p": 5
  },
  {
    "name": "Meletius of Lycopolis",
    "birth_range": [250, 260],
    "death_range": [325, 330],
    "category": ["bishop", "schismatic_leader"],
    "biography": "Egyptian bishop whose rigorist schism produced the Meletian movement, which remained significant into the period of the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "His movement was schismatic rather than straightforwardly doctrinally heretical.",
    "p": 5
  },

  {
    "name": "Athanasius of Alexandria",
    "birth_range": [295, 298],
    "death_range": [373, 373],
    "category": ["bishop", "writer", "confessor", "saint"],
    "biography": "Deacon and secretary to Alexander of Alexandria at Nicaea, later bishop of Alexandria and the great defender of Nicene faith against Arianism.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "A central figure in the Nicene controversy and one of the most important theologians of the fourth-century Church.",
    "p": 2
  },
  {
    "name": "Anthony the Great",
    "birth_range": [251, 251],
    "death_range": [356, 356],
    "category": ["monk", "ascetic", "saint"],
    "biography": "Egyptian ascetic traditionally regarded as one of the founders of Christian monasticism and a model of the solitary life.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His life, written by Athanasius, became enormously influential in spreading the ideal of Christian monasticism.",
    "p": 3
  },
  {
    "name": "Alexander of Alexandria",
    "birth_range": [250, 260],
    "death_range": [326, 328],
    "category": ["bishop", "writer", "saint"],
    "biography": "Bishop of Alexandria who opposed Arius and whose theological position helped lead to the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Athanasius served as his deacon and secretary.",
    "p": 3
  },
  {
    "name": "Arius",
    "birth_range": [250, 260],
    "death_range": [336, 336],
    "category": ["presbyter", "writer", "heretic"],
    "biography": "Alexandrian presbyter whose teaching concerning the relationship between the Father and the Son provoked the Arian controversy and the Council of Nicaea.  Founder of Arianism.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "The Nicene Council condemned his teaching; later forms of Arianism continued to influence parts of the Roman Empire.",
    "p": 3
  },
  {
    "name": "Hosius of Corduba",
    "birth_range": [256, 257],
    "death_range": [357, 359],
    "category": ["bishop", "confessor"],
    "biography": "Spanish bishop and influential adviser to Constantine who played a major role in the organization of the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "One of the most important ecclesiastical leaders of the Nicene generation.",
    "p": 5
  },
  {
    "name": "Eusebius of Caesarea",
    "birth_range": [260, 265],
    "death_range": [339, 340],
    "category": ["bishop", "writer"],
    "biography": "Bishop of Caesarea and author of the first major surviving history of the Christian Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His theological position during the Arian controversy was complex, but he was not a simple representative of the later Arian movement.",
    "p": 4
  },
  {
    "name": "Eusebius of Nicomedia",
    "birth_range": [260, 270],
    "death_range": [341, 342],
    "category": ["bishop", "writer"],
    "biography": "Powerful fourth-century bishop and leading supporter of Arius and the anti-Nicene theological coalition.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "His precise theological classification is complicated by the diversity of positions within the anti-Nicene movement, but he is generally associated with the Arian cause.",
    "p": 4
  },
  {
    "name": "Pachomius the Great",
    "birth_range": [292, 298],
    "death_range": [346, 348],
    "category": ["monk"],
    "biography": "Egyptian ascetic traditionally regarded as the founder of organized cenobitic monasticism.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His communities helped transform monasticism from a collection of solitary ascetics into organized communal institutions.",
    "p": 3
  },
  {
    "name": "Macarius of Egypt",
    "birth_range": [295, 305],
    "death_range": [390, 391],
    "category": ["monk"],
    "biography": "Egyptian desert father and major representative of the early eremitic monastic tradition.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "medium",
    "notes": "Some traditions and writings associated with the name Macarius are difficult to assign with certainty to the historical individual.",
    "p": 3
  },
  {
    "name": "Paphnutius of Thebes",
    "birth_range": [250, 270],
    "death_range": [350, 360],
    "category": ["bishop", "confessor", "monk"],
    "biography": "Egyptian bishop and confessor who suffered during the Great Persecution and was associated with the Nicene generation.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "The details of his life are partly preserved through later tradition.",
    "p": 4
  },
  {
    "name": "Spyridon of Trimythous",
    "birth_range": [250, 270],
    "death_range": [348, 350],
    "category": ["bishop", "confessor"],
    "biography": "Cypriot bishop and former shepherd traditionally remembered as a participant in the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "notes": "A prominent figure in Orthodox tradition; the details of his biography are heavily shaped by later hagiography.",
    "p": 4
  },
  {
    "name": "James of Nisibis",
    "birth_range": [250, 270],
    "death_range": [338, 350],
    "category": ["bishop", "monk", "ascetic"],
    "biography": "Bishop of Nisibis and major Syriac Christian ascetic traditionally associated with the Council of Nicaea.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "high",
    "notes": "An important representative of the eastern and Syriac Christian world.",
    "p": 5
  },
  {
    "name": "Ephrem the Syrian",
    "birth_range": [306, 307],
    "death_range": [373, 373],
    "category": ["deacon", "writer", "poet", "ascetic"],
    "biography": "Syriac Christian poet, theologian, and hymnographer whose writings became foundational to the spiritual and liturgical tradition of Syriac Christianity.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "His life and work connect the Nicene era with the flourishing of fourth-century Christian theology and hymnography.",
    "p": 2
  },
  {
    "name": "Hilary of Poitiers",
    "birth_range": [310, 320],
    "death_range": [367, 368],
    "category": ["bishop", "writer", "confessor"],
    "biography": "Western bishop and theologian who became one of the principal defenders of Nicene theology against Arianism in the Latin-speaking Church.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "notes": "Often called the 'Athanasius of the West' for his defense of Nicene faith.",
    "p": 4
  },
//  {
//    "name": "Eusebius of Vercelli",
//    "birth_range": [283, 290],
//    "death_range": [371, 371],
//    "category": ["bishop", "confessor"],
//    "biography": "Western bishop who suffered exile for defending the Nicene faith during the Arian controversy.",
//    "date_basis": "historical_tradition",
//    "date_confidence": "medium",
//    "identity_confidence": "high",
//    "notes": "An important representative of the Western Nicene resistance.",
//    "p": 4
//  },
  {
    "name": "Lucifer of Cagliari",
    "birth_range": [290, 300],
    "death_range": [370, 371],
    "category": ["bishop", "confessor", "schismatic_leader"],
    "biography": "Sardinian bishop and fierce opponent of Arianism whose rigorist response to the restoration of former Arian bishops contributed to the Luciferian schism.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "heretic": true,
    "notes": "A useful example of the distinction between doctrinal orthodoxy and later schism.",
    "p": 5
  },

  {
    "name": "Photini",
    "birth_range": [0, 20],
    "death_range": [65, 100],
    "category": ["martyr"],
    "biography": "The Samaritan Woman whom Christ met at the well, traditionally remembered as a missionary and martyr after proclaiming Christ to others.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "historicity": "traditional",
    "notes": "The Gospel identifies the woman but does not give her name; Photini is the traditional name in Eastern Christianity.",
    "p": 4
  },
  {
    "name": "Longinus",
    "birth_range": [0, 20],
    "death_range": [30, 100],
    "category": ["soldier", "martyr"],
    "biography": "Traditional Roman soldier associated with the Crucifixion and with the confession of Christ after witnessing His death.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The Gospel of John does not name the soldier who pierced Christ's side; Longinus is the later traditional identification.",
    "p": 4
  },
  {
    "name": "Stephen",
    "birth_range": [0, 10],
    "death_range": [34, 37],
    "category": ["deacon", "martyr"],
    "biography": "One of the Seven appointed in Jerusalem and the first Christian martyr recorded in the New Testament.",
    "date_basis": "traditional_estimate",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "His martyrdom is narrated in Acts 6–7.",
    "p": 3
  },
  {
    "name": "Perpetua",
    "birth_range": [180, 185],
    "death_range": [203, 203],
    "category": ["martyr", "noblewoman"],
    "biography": "Young Christian noblewoman whose prison diary and martyrdom account provide one of the most personal surviving voices from the age of persecution.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Martyred at Carthage during the persecution of Septimius Severus.",
    "p": 3
  },
//  {
//    "name": "Speratus",
//    "birth_range": [150, 175],
//    "death_range": [180, 203],
//    "category": ["martyr"],
//    "biography": "Leader among the Scillitan Martyrs, among the earliest securely documented Christian martyrs in Roman North Africa.",
//    "date_basis": "historical",
//    "date_confidence": "medium",
//    "identity_confidence": "high",
//    "historicity": "historical",
//  //  "notes": "The Scillitan Martyrs were executed in 180.",
//    "p": 5
//  },
  {
    "name": "Pothinus of Lyons",
    "birth_range": [80, 90],
    "death_range": [177, 177],
    "category": ["bishop", "martyr", "missionary"],
    "biography": "First bishop of Lyons and leader of the Christian community during the persecution of 177.",
    "date_basis": "historical_tradition",
    "date_confidence": "medium",
    "identity_confidence": "high",
    "historicity": "historical",
    "notes": "Among the earliest known bishops and martyrs of the Church in Gaul.",
    "p": 2
  },
  {
    "name": "Thecla",
    "birth_range": [20, 40],
    "death_range": [80, 100],
    "category": ["missionary", "ascetic", "martyr", "traditional_figure"],
    "biography": "Traditional disciple of Paul who became one of the most influential female saints of early Christianity and a model of virginity and ascetic devotion.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "medium",
    "historicity": "traditional",
    "notes": "The Acts of Paul and Thecla is an early Christian text, but the details of her biography are difficult to establish historically.",
    "p": 5
  },
  {
    "name": "Nicholas of Myra",
    "birth_range": [270, 290],
    "death_range": [343, 350],
    "category": ["bishop", "confessor"],
    "biography": "Bishop of Myra remembered for generosity, pastoral charity, and steadfastness during the era of persecution, later becoming one of the most beloved saints of the Christian world.",
    "date_basis": "historical_tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "A historical bishop probably existed, but the details of the familiar biography are heavily shaped by later tradition.",
    "p": 2
  },
  {
    "name": "Sebastian of Rome",
    "birth_range": [250, 270],
    "death_range": [288, 305],
    "category": ["soldier", "martyr"],
    "biography": "Traditional Roman soldier and Christian martyr remembered for encouraging persecuted Christians and suffering execution for the faith.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "A highly influential martyr in later Christian devotion, though the details of his biography are uncertain.",
    "p": 4
  },
  {
    "name": "St. George",
    "birth_range": [270, 285],
    "death_range": [303, 305],
    "category": ["soldier", "martyr"],
    "biography": "Soldier and great martyr from Lydda whose steadfastness under persecution made him one of the most widely venerated saints of the early Church.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "p": 3
  },
  {
    "name": "Victor of Marseilles",
    "birth_range": [230, 260],
    "death_range": [303, 304],
    "category": ["soldier", "martyr"],
    "biography": "Traditional Christian soldier martyred at Marseilles during the persecution under Diocletian.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "A representative of the many military martyrs remembered from the Great Persecution.",
    "p": 5
  },
//  {
//    "name": "Maurice of the Theban Legion",
//    "birth_range": [250, 270],
//    "death_range": [285, 305],
//    "category": ["soldier", "martyr"],
//    "biography": "Traditional commander of the Theban Legion, remembered as a Christian soldier who refused to participate in persecution and was martyred with his companions.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "The historical details of the Theban Legion account are debated.",
//    "p": 5
//  },
  {
    "name": "Lucy of Syracuse",
    "birth_range": [280, 290],
    "death_range": [304, 304],
    "category": ["martyr", "virgin"],
    "biography": "Sicilian Christian virgin and martyr associated with the persecution of Diocletian.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "One of the most widely venerated female martyrs of late antiquity.",
    "p": 4
  },
  {
    "name": "Catherine of Alexandria",
    "birth_range": [280, 290],
    "death_range": [305, 320],
    "category": ["martyr", "virgin"],
    "biography": "Alexandrian virgin and martyr remembered for her wisdom, steadfastness, and confrontation with pagan authority.  St Catharine's monastery in Egypt is named after her.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "p": 3
  },

  {
    "name": "St. Dmitri",
    "birth_range": [270, 285],
    "death_range": [303, 306],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "Great-martyr of Thessalonica and one of the most important military saints.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "His traditional commemoration is closely associated with the persecution under Maximian; the details of his biography are difficult to establish independently.",
    "p": 3
  },
//  {
//    "name": "Nestor of Thessalonica",
//    "birth_range": [280, 295],
//    "death_range": [303, 306],
//    "category": ["martyr", "young_martyr"],
//    "biography": "Young man traditionally instructed and encouraged by Demetrius, who defeated the pagan champion Lyaios before being martyred.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "medium",
//    "historicity": "traditional_historical",
//    "notes": "The traditional account explicitly presents him as a disciple or spiritual protégé of Demetrius.",
//    "p": 5
//  },
  {
    "name": "Theodore the Recruit",
    "birth_range": [270, 285],
    "death_range": [306, 306],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "Soldier traditionally martyred at Euchaita after refusing to sacrifice to pagan gods.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "Also known as Theodore Tiro or Theodore the Recruit.",
    "p": 5
  },
  {
    "name": "Theodore Stratelates",
    "birth_range": [270, 285],
    "death_range": [319, 319],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "Military commander who was martyred after publicly confessing Christ.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The relationship between the traditions of Theodore Stratelates and Theodore the Recruit is historically complicated.",
    "p": 5
  },
  {
    "name": "Menas of Egypt",
    "birth_range": [270, 285],
    "death_range": [304, 310],
    "category": ["soldier", "martyr", "great_martyr"],
    "biography": "Egyptian soldier who renounced military service and was martyred for refusing to deny Christ.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "medium",
    "historicity": "traditional_historical",
    "notes": "One of the most widely venerated military martyrs of Egypt and the Christian East.",
    "p": 4
  },
  {
    "name": "Mercurius of Caesarea",
    "birth_range": [220, 250],
    "death_range": [250, 270],
    "category": ["soldier", "martyr"],
    "biography": "Soldier and martyr who became one of the most prominent military saints of the East.",
    "date_basis": "tradition",
    "date_confidence": "low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "The chronology of the different traditions associated with Mercurius is uncertain.",
    "p": 3
  },

//  {
//    "name": "Anastasia of Sirmium",
//    "birth_range": [270, 285],
//    "death_range": [304, 305],
//    "category": ["martyr", "great_martyr"],
//    "biography": "Christian woman traditionally martyred during the Great Persecution and remembered for ministering to imprisoned Christians.",
//    "date_basis": "tradition",
//    "date_confidence": "low",
//    "identity_confidence": "medium",
//    "historicity": "traditional_historical",
//  //  "notes": "One of the most important female martyrs of the late Roman persecutions.",
//    "p": 5
//  },
  {
    "name": "Barbara of Heliopolis",
    "birth_range": [270, 290],
    "death_range": [305, 320],
    "category": ["virgin", "martyr", "great_martyr"],
    "biography": "Virgin and martyr remembered for refusing to renounce Christ despite opposition from her father.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "One of the most prominent traditional female martyrs of the Great Persecution.",
    "p": 4
  },
  {
    "name": "Marina of Antioch",
    "birth_range": [270, 290],
    "death_range": [304, 320],
    "category": ["virgin", "martyr", "great_martyr"],
    "biography": "Virgin and martyr remembered for steadfastness under persecution.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "Known in the West as Margaret of Antioch; the historical basis of the developed legend is uncertain.",
    "p": 4
  },
  {
    "name": "Irene of Thessalonica",
    "birth_range": [270, 290],
    "death_range": [304, 305],
    "category": ["virgin", "martyr"],
    "biography": "Virgin and martyr associated with the persecution of Diocletian.",
    "date_basis": "tradition",
    "date_confidence": "very_low",
    "identity_confidence": "low",
    "historicity": "traditional",
    "notes": "Often remembered together with her sisters Agape and Chionia.",
    "p": 4
  },
//  {
//    "name": "Mariamne",
//    "birth_range": [0, 20],
//    "death_range": [50, 100],
//    "category": ["missionary"],
//    "biography": "Traditional sister of the Apostle Philip and missionary associated with the early spread of the Gospel.",
//    "date_basis": "tradition",
//    "date_confidence": "very_low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "A significant traditional female missionary of the apostolic age.",
//    "p": 5
//  },
//  {
//    "name": "Domnina",
//    "birth_range": [20, 50],
//    "death_range": [65, 100],
//    "category": ["martyr"],
//    "biography": "Traditional daughter of the Emperor Nero who is remembered as a convert to Christianity and companion of Photini in martyrdom.",
//    "date_basis": "tradition",
//    "date_confidence": "very_low",
//    "identity_confidence": "low",
//    "historicity": "traditional",
//  //  "notes": "Part of the traditional Photini martyr cycle.",
//    "p": 5
//  },
//  {
//    "name": "Constantius II",
//    "birth_range": [317, 317],
//    "death_range": [361, 361],
//    "category": ["emperor", "political_ruler"],
//    "biography": "Roman emperor whose reign was dominated by conflict between Nicene and various non-Nicene Christian factions.",
//    "date_basis": "historical",
//    "date_confidence": "high",
//    "identity_confidence": "high",
//  //  "notes": "Not a Church figure, but highly relevant to the political history of the Nicene controversy.",
//    "p": 5
//  },
  {
    "name": "Constantine the Great",
    "birth_range": [272, 274],
    "death_range": [337, 337],
    "category": ["emperor", "political_ruler"],
    "biography": "Roman emperor who ended the great persecutions, legalized Christianity, and convened the Council of Nicaea.",
    "date_basis": "historical",
    "date_confidence": "high",
    "identity_confidence": "high",
    "notes": "A decisive political figure in the transition from the persecuted Church to the publicly established Christian Church.",
    "p": 2
  }
];
